### ISSUE TITLE
Ability to set server flood protection settings

### ISSUE THREAD

**Issue by tecknojock** [magne4000/quassel-webserver#181]
Well, now that its officially included in the core, it'd be nice for the web server to be able to set this setting as well, if the core its connected to is late enough.

**Comment by magne4000** [comment]
Where is this new setting located ?

**Comment by tecknojock** [comment]
Here's the pull request that added it to the master: https://github.com/quassel/quassel/pull/236

Unfortunately I havn't figured out how to cross compile a windows client so I'm waiting for the next release to be able to have access to the feature on the desktop.

**Comment by digitalcircuit** [comment]
Thanks for filing an issue here, @tecknojock!

*Aside, for Windows you can probably use one of [Quassel's AppVeyor builds](https://ci.appveyor.com/project/Quassel/quassel/history ) - click on one that's not a pull request, go to ```msvc2015``` 64-bit or 32-bit depending, and download the installer from the Artifacts tab.  Note that there's currently a bug where the Visual Studio 2013 Runtime is also required due to precompiled OpenSSL.  @TheOneRing was still investigating it.*

Eventually I intend to entirely rewrite Quassel's rate-limiting to follow what IRC servers actually do - limit according to bytes sent per unit of time.  HexChat currently does this.  That said, it's a risky change, other responsibilities mean I probably won't get to it soon, and I'll try to make changes as easy as possible to handle upgrading anyways, so...

In short, implementing what's currently in ```0.13-git``` should be fine :)

### Notable changes for rate limits
* [Additional synced properties to Network object](https://github.com/quassel/quassel/blob/8443ab1e0a812d76d5efa816d5bd3d476d67ab2d/src/common/network.h#L77-L81 )
 * [Doxygen comments on properties](https://github.com/quassel/quassel/blob/8443ab1e0a812d76d5efa816d5bd3d476d67ab2d/src/common/network.h#L343-L383 )
 * [Protocol range enforcements](https://github.com/quassel/quassel/blob/8443ab1e0a812d76d5efa816d5bd3d476d67ab2d/src/common/network.cpp#L696-L743 )
 * **NOTE**: don't allow setting ```setMessageRateDelay``` to ```0```, either.  This is [fixed in Quassel PR #252](https://github.com/quassel/quassel/pull/252 )
 * [Settings UI code, including enable checkbox, minimum/expected values](https://github.com/quassel/quassel/blob/8443ab1e0a812d76d5efa816d5bd3d476d67ab2d/src/qtui/settingspages/networkssettingspage.ui#L499-L644 )
* [Core ```Feature``` flag to detect if available: ```CustomRateLimits = 0x0080```](https://github.com/quassel/quassel/blob/8443ab1e0a812d76d5efa816d5bd3d476d67ab2d/src/common/quassel.h#L76 )

**Comment by magne4000** [comment]
Thank you @digitalcircuit for all those details
