### ISSUE TITLE
Cannot fetch backlog using arrow keys (or scrollbar events)

### ISSUE THREAD

**Issue by waddlesplash** [magne4000/quassel-webserver#21]
There are a lot of devices that do not have a scrollwheel (e.g. laptops). It'd be nice to be able to fetch backlog by just pressing "up" on the scrollbar or pressing the "up" arrow key while the chat view is focused.

**Comment by magne4000** [comment]
I began a new branch [angular](https://github.com/magne4000/quassel-webserver/tree/angular) to migrate the UI to [AngularJS framework](https://angularjs.org/).This issue is fixed in that branch, but as the migration is not completed, I do not recommend to switch to [angular](https://github.com/magne4000/quassel-webserver/tree/angular) branch for "production" use.
It should be merge soon into master.
